'use strict';
const CRM={classId:null,people:[],selected:null,notes:[],drafts:{},colors:['#ffffff','#f9c7c7','#f8dda6','#d5edc6','#bfe4f6','#d8ccf3'],statuses:{Anwesend:'#22c55e',Abwesend:'#ef4444',Teams:'#3b82f6'}};
async function crmLoad(){const container=$('#crm'),classId=cls.id;const people=await request('crmList',{classId});if(!container?.isConnected||cls?.id!==classId||boot?.role!=='host')return;CRM.classId=classId;CRM.people=people;container.innerHTML='<div class="crm-grid" id="crm-grid"></div><div id="crm-popup" class="crm-popup" hidden></div><dialog id="crm-drawer" class="crm-drawer" aria-labelledby="crm-name"><button id="crm-name" class="crm-name" data-crm="close" title="Zurück zur Klasse"></button><textarea id="crm-text" maxlength="10000" aria-label="Neuer Kommentar" placeholder="Neuen Eintrag schreiben …"></textarea><p class="muted">Enter speichert · Umschalt+Enter für einen Zeilenumbruch</p><p id="crm-error" role="status"></p><div id="crm-notes"></div></dialog>';crmGrid()}
function crmGrid(){const grid=$('#crm-grid');if(!grid)return;grid.innerHTML=CRM.people.map(n=>`<section class="crm-tile" style="background:${n.color}" data-crm-person="${esc(n.id)}" tabindex="0" aria-label="${esc(n.name)}: Farbe wählen; Enter öffnet Kommentare" title="Klick: Farbe · Doppelklick: Kommentare"><div class="crm-tile-header"><span>${esc(n.name)}</span><button data-crm="status" data-person="${esc(n.id)}" class="crm-status" style="color:${CRM.statuses[n.status]||'#17233a'}" aria-label="Status für ${esc(n.name)}: ${esc(n.status||'Nicht markiert')}" title="${esc(n.status||'Status')}">●</button></div><button class="crm-comments" data-crm="open" data-person="${esc(n.id)}" aria-label="Kommentare für ${esc(n.name)}">✎</button></section>`).join('')+'<button class="crm-add" data-crm="add" aria-label="Teilnehmer hinzufügen" title="Teilnehmer hinzufügen">＋</button><button class="crm-reset" data-crm="reset" aria-label="Anwesenheit zurücksetzen" title="Anwesenheit zurücksetzen">↺</button>'}
function crmHidePopup(){const p=$('#crm-popup');if(p)p.hidden=true}
function crmPopup(anchor,id,status){const p=$('#crm-popup');p.innerHTML=status?Object.entries(CRM.statuses).map(([label,color])=>`<button data-crm="mark" data-person="${esc(id)}" data-status="${label}" aria-label="${label}"><span style="color:${color}">●</span> ${label}</button>`).join('')+`<button data-crm="mark" data-person="${esc(id)}" data-status="">Markierung entfernen</button>`:CRM.colors.map((color,i)=>`<button data-crm="color" data-person="${esc(id)}" data-color="${color}" style="background:${color}" aria-label="${['Weiß','Rot','Gelb','Grün','Blau','Violett'][i]}"></button>`).join('');p.classList.toggle('crm-palette',!status);p.hidden=false;const r=anchor.getBoundingClientRect();p.style.left=Math.max(8,Math.min(r.left,innerWidth-p.offsetWidth-8))+'px';p.style.top=Math.max(8,Math.min(r.bottom+6,innerHeight-p.offsetHeight-8))+'px'}
async function crmOpen(id){crmHidePopup();CRM.selected=id;const person=CRM.people.find(n=>n.id===id),dialog=$('#crm-drawer');$('#crm-name').textContent=person.name+' · Zurück';$('#crm-text').value=CRM.drafts[id]||'';$('#crm-notes').textContent='Kommentare werden geladen …';$('#crm-error').textContent='';dialog.showModal();await crmLoadNotes(id,CRM.classId);$('#crm-text')?.focus()}
async function crmLoadNotes(person,classId){const notes=await request('crmNotes',{person,classId});if(CRM.selected!==person||CRM.classId!==classId||!$('#crm-notes'))return;CRM.notes=notes;$('#crm-notes').innerHTML=notes.length?notes.map(n=>`<div class="crm-note"><span>${esc(n.body)}</span><div><time>${new Date(n.created).toLocaleString('de-DE')}</time><div class="crm-note-actions"><button data-crm="edit" data-note="${esc(n.id)}" aria-label="Kommentar bearbeiten">✎</button><button data-crm="delete" data-note="${esc(n.id)}" aria-label="Kommentar löschen">🗑</button></div></div></div>`).join(''):'<p class="muted">Noch keine Einträge.</p>'}
async function crmSave(){const field=$('#crm-text');if(!field||field.disabled||!field.value.trim())return;const body=field.value,person=CRM.selected,classId=CRM.classId;field.disabled=true;try{await request('crmNoteAdd',{classId,person,body,requestId:crypto.randomUUID()});CRM.drafts[person]='';if(CRM.selected===person&&field.isConnected)field.value='';await crmLoadNotes(person,classId)}catch(e){if($('#crm-error'))$('#crm-error').textContent=e.message}finally{field.disabled=false;field.focus()}}
document.addEventListener('input',e=>{if(e.target.id==='crm-text')CRM.drafts[CRM.selected]=e.target.value});
document.addEventListener('keydown',e=>{if(e.target.id==='crm-text'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();crmSave()}const tile=e.target.closest('[data-crm-person]');if(tile&&e.target===tile&&e.key==='Enter'){e.preventDefault();crmOpen(tile.dataset.crmPerson).catch(showError)}if(e.key==='Escape')crmHidePopup()});
document.addEventListener('dblclick',e=>{const tile=e.target.closest('[data-crm-person]');if(tile&&!e.target.closest('button'))crmOpen(tile.dataset.crmPerson).catch(showError)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-crm]'),tile=e.target.closest('[data-crm-person]');if(!b){if(tile)crmPopup(tile,tile.dataset.crmPerson,false);else if(!e.target.closest('#crm-popup'))crmHidePopup();return}const act=b.dataset.crm,id=b.dataset.person,classId=CRM.classId;if(act==='status')return crmPopup(b,id,true);if(act==='close')return $('#crm-drawer').close();guarded(async()=>{
 if(act==='open')return crmOpen(id);
 if(act==='add'){const name=prompt('Vorname:');if(!name?.trim())return;await request('crmAdd',{classId,name,requestId:crypto.randomUUID()});return crmLoad()}
 if(act==='reset'){if(!confirm('Anwesenheit aller Teilnehmer zurücksetzen?'))return;await request('crmReset',{classId});CRM.people.forEach(n=>n.status='');crmHidePopup();return crmGrid()}
 if(act==='color'||act==='mark'){const patch=act==='color'?{color:b.dataset.color}:{status:b.dataset.status};await request('crmMark',{classId,person:id,...patch});if(CRM.classId!==classId)return;Object.assign(CRM.people.find(n=>n.id===id),patch);crmHidePopup();return crmGrid()}
 if(act==='edit'||act==='delete'){const person=CRM.selected,note=b.dataset.note;if(act==='edit'){const body=prompt('Notiz bearbeiten:',CRM.notes.find(n=>n.id===note).body);if(!body?.trim())return;await request('crmNoteEdit',{classId,person,note,body})}else await request('crmNoteDelete',{classId,person,note});await crmLoadNotes(person,classId)}
 },b)});
