'use strict';
function richAnswer(t,a=[]){if(t.kind==='budget')return Array.from({length:4},(_,i)=>a[i]||'');if(t.kind!=='matrix')return a;const out=[...a];t.rows.forEach((r,i)=>{if(t.fixedCriteria)out[i*5]=r.criterion;if(t.fixedWeights)out[i*5+1]=String(r.weight)});return out}
function richComplete(t,a){if(t.kind==='budget')return a[0]==='possible'?!!(a[2]&&a[3]):a[0]==='impossible'&&!!a[1]?.trim()&&Number.isFinite(Number(a[1].replace(',','.')));if(t.kind==='why')return a.length>=2;if(t.kind==='trace')return a.length===t.fields.length&&a.every(v=>v!==undefined&&v.trim());if(t.kind==='matrix')return a.length===t.fields.length&&Array.from(a).every(v=>v!==undefined&&v!=='');return null}
function richTask(t,a,locked,scope){
 const attrs=i=>scope==='practice'?`data-practice-field="${i}"`:`data-answer-index="${i}"`,off=locked?'disabled':'';
 if(t.kind==='trueFalseDragging')return `<div class="truth-tokens">${t.choices.map(c=>`<button type="button" draggable="${!locked}" data-truth-token="${esc(c.id)}" ${off}>${esc(c.label)}</button>`).join('')}</div><div class="truth-rows">${t.fields.map((text,i)=>`<label class="truth-row" data-truth-drop="${i}"><span>${esc(text)}</span><select ${attrs(i)} ${off}><option value="">Zuordnen</option>${t.choices.map(c=>`<option value="${esc(c.id)}" ${a[i]===c.id?'selected':''}>${esc(c.label)}</option>`).join('')}</select></label>`).join('')}</div>`;
 if(t.kind==='risk')return `<div class="matrix-scroll"><table><thead><tr><th>Risiko</th><th>Wahrscheinlichkeit</th><th>Schadenshöhe</th></tr></thead><tbody>${t.risks.map((r,i)=>`<tr><th>${esc(r.name)}<small>${esc(r.detail)}</small></th>${[0,1].map(j=>`<td><select ${attrs(i*2+j)} ${off}><option value="">Auswählen</option>${['1','2','3','4','5'].map(v=>`<option value="${v}" ${a[i*2+j]===v?'selected':''}>${v}</option>`).join('')}</select></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 if(t.kind==='budget')return `<label>Deine Einschätzung<select ${attrs(0)} data-budget-feasibility ${off}><option value="">Bitte auswählen</option><option value="possible" ${a[0]==='possible'?'selected':''}>Alle Anforderungen sind finanzierbar.</option><option value="impossible" ${a[0]==='impossible'?'selected':''}>Das Budget reicht nicht aus.</option></select></label><label>Mindestkosten in Euro<input ${attrs(1)} inputmode="decimal" value="${esc(a[1])}" ${locked||a[0]!=='impossible'?'disabled':''}></label>${['ram','ssd'].map((group,i)=>`<label>${group==='ram'?'RAM-Angebot':'SSD-Angebot'}<select ${attrs(i+2)} ${locked||a[0]!=='possible'?'disabled':''}><option value="">Bitte auswählen</option>${t.items.filter(x=>x.group===group).map(x=>`<option value="${esc(x.id)}" ${a[i+2]===x.id?'selected':''}>${esc(x.text)} · ${x.cost} €</option>`).join('')}</select></label>`).join('')}`;
 if(t.kind==='why'){const d=t.decisions.find(d=>d.id===a[0]);return `<div class="answers">${t.decisions.map(d=>`<button data-rich-decision="${esc(d.id)}" data-rich-scope="${scope}" class="answer ${a[0]===d.id?'selected':''}" ${off}>${esc(d.label)}</button>`).join('')}</div>${d?`<p>${d.mode==='multi'?'Wähle die passenden Begründungen.':'Wähle die passende Begründung.'}</p><div class="answers">${d.reasons.map(id=>`<button data-rich-reason="${esc(id)}" data-rich-scope="${scope}" class="answer ${a.includes(id)?'selected':''}" ${off}>${esc(t.choices.find(c=>c.id===id).label)}</button>`).join('')}</div>`:''}`}
 if(t.kind==='trace')return `<pre class="trace-code">${esc(t.code)}</pre>${t.fields.map((f,i)=>`<label class="field">${esc(f)}<input ${attrs(i)} inputmode="decimal" value="${esc(a[i]||'')}" ${off}></label>`).join('')}`;
 if(t.kind==='matrix'){const select=(i,options)=>`<select ${attrs(i)} ${off}><option value="">Bitte auswählen</option>${options.map(v=>`<option value="${esc(v)}" ${String(a[i])===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select>`;return `<div class="matrix-scroll"><table><thead><tr><th>Kriterium</th><th>Gewichtung %</th>${t.offers.map(o=>`<th>${esc(o)}</th>`).join('')}</tr></thead><tbody>${t.rows.map((r,i)=>`<tr><th>${t.fixedCriteria?esc(r.criterion):select(i*5,t.criteria)}</th><td>${t.fixedWeights?r.weight:select(i*5+1,[10,20,30,40,50,60])}</td>${r.values.map((v,j)=>`<td>${esc(v)}${select(i*5+2+j,[1,2,3])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
 return null;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-rich-scope]');if(!b||b.disabled)return;const practice=b.dataset.richScope==='practice',t=practice?P.round.tasks[P.round.position]:quiz.question;let a=practice?(P.round.draft[t.key]||[]):quizDraft;if(b.dataset.richDecision)a=[b.dataset.richDecision];else{const d=t.decisions.find(d=>d.id===a[0]),id=b.dataset.richReason;a=d.mode==='multi'?(a.includes(id)?a.filter(v=>v!==id):[...a,id]):[a[0],id]}
 if(practice){P.round.draft[t.key]=a;practiceSave();drawPracticeRound()}else{quizDraft=a;drawQuiz()}
});
let truthToken=null;
document.addEventListener('dragstart',e=>{const b=e.target.closest('[data-truth-token]');if(b&&!b.disabled)e.dataTransfer.setData('text/plain',b.dataset.truthToken);});
document.addEventListener('dragover',e=>{const row=e.target.closest('[data-truth-drop]');if(row&&!row.querySelector('select').disabled)e.preventDefault();});
function setTruth(row,value){if(!row||!['true','false'].includes(value))return;const select=row.querySelector('select');if(select.disabled)return;select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));}
document.addEventListener('drop',e=>{const row=e.target.closest('[data-truth-drop]');if(row){e.preventDefault();setTruth(row,e.dataTransfer.getData('text/plain'));}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-truth-token]');if(b&&!b.disabled){truthToken=b.dataset.truthToken;document.querySelectorAll('[data-truth-token]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));return;}if(!e.target.closest('select,option'))setTruth(e.target.closest('[data-truth-drop]'),truthToken);});
document.addEventListener('change',e=>{if(e.target.hasAttribute('data-budget-feasibility'))queueMicrotask(()=>{if(view==='practice')drawPracticeRound();else if(view==='quiz')drawQuiz();});});
